# Generated by Django 6.0.3 on 2026-04-17 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('mon_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tues_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wed_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('thurs_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fri_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sat_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sun_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
    ]